steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/studio-9105849211-9ba48/authentication-service:latest
      - --cache=true
      - --cache-ttl=168h
      - --dockerfile=packages/services/authentication-service/Dockerfile
      - --build-arg=CACHE_BUSTER=$BUILD_ID

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'authentication-service'
      - '--image=gcr.io/studio-9105849211-9ba48/authentication-service:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--timeout=300'
timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY


