import { DocumentReader } from '@/components/legal/DocumentReader';
import { DocumentVaultCallout } from '@/components/legal/DocumentVaultCallout';

export default function LPAPage() {
  return (
    <DocumentReader>
      <section className="guildhall-document-intro" aria-labelledby="vault-title"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center border border-guildhall-consensus/40 bg-guildhall-consensus/10 text-guildhall-consensus">01</span><div><p className="guildhall-kicker text-guildhall-consensus">Public alignment summary</p><p className="mt-1 text-sm text-guildhall-muted">How the legal covenants map to the smart-contract system.</p></div></div><div className="mt-8 border border-guildhall-line bg-guildhall-panel-raised p-5 sm:p-6"><h2 id="vault-title" className="font-command text-2xl font-semibold">Secure document vault</h2><p className="mt-3 text-base leading-7 text-guildhall-muted">The full execution copy requires a sovereign signature. This preview keeps the core structure readable before access is requested.</p></div></section>
      <article className="guildhall-prose mt-12"><h2>Article II: Master-Series Architecture</h2><p>Establishes the segregation of assets, liabilities, and bookkeeping pursuant to Delaware DRULPA Section 17-218. On-chain, this isolation is enforced by the TPNS Platform Factory. The parent platform deploys independent smart-contract instances (Series Tokens) for each physical asset class.</p><h2>Article IV: The 3-Tier Execution Matrix</h2><p>Outlines the strict parameterization of assets into yield profiles: Cash Flow, Capital Gain, and High Complexity.</p><ul><li><strong>Tier 1:</strong> Predictable cash flow (for example, NNN industrial).</li><li><strong>Tier 2:</strong> Value-add and capital gains (for example, multi-family conversions).</li><li><strong>Tier 3:</strong> High complexity (for example, distressed aggregation and quiet-title pipelines).</li></ul><h2>Article V: The 21/30/49 Metabolic Waterfall</h2><p>Defines the flow of free cash flow after labor deductions (Tau). This distribution is applied to TPNS personal holdings and is a suggested structure for independent fund managers building on the platform. The covenant is modeled in the <code>distributeYield()</code> function of the blockchain contracts.</p><ul><li><strong>49%</strong> — Investor capital (LPs)</li><li><strong>30%</strong> — The Commons (network treasury for continued land acquisition)</li><li><strong>21%</strong> — Governance and operator pool</li></ul></article>
      <DocumentVaultCallout />
    </DocumentReader>
  );
}
