import React from 'react';
import { Badge } from '@promethea/ui';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@promethea/ui';
import { RealityBadge } from './layout/RealityBadge';

interface LedgerValueProps {
    value: number | string;
    isSimulated?: boolean;
    currency?: string;
    className?: string;
}

export function LedgerValue({ value, isSimulated = false, currency = '$', className = '' }: LedgerValueProps) {
    const formattedValue = typeof value === 'number' 
        ? `${currency}${value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
        : value;

    if (isSimulated) {
        return (
            <TooltipProvider>
                <Tooltip>
                    <TooltipTrigger asChild>
                        <div className={`inline-flex items-center gap-2 ${className}`}>
                            <span className="text-amber-500 font-mono opacity-80 decoration-dashed underline decoration-amber-500/50 cursor-help">
                                {formattedValue}
                            </span>
                            <RealityBadge state="SIMULATED" size="sm" />
                        </div>
                    </TooltipTrigger>
                    <TooltipContent className="bg-amber-950 border-amber-500/50 text-amber-200">
                        <p className="max-w-xs text-xs">
                            This structural metric is generated by simulated architectural protocols. It does not reflect verified on-chain or CEX liquidity.
                        </p>
                    </TooltipContent>
                </Tooltip>
            </TooltipProvider>
        );
    }

    // Physical / Live Data styling
    return (
        <TooltipProvider>
            <Tooltip>
                <TooltipTrigger asChild>
                    <div className={`inline-flex items-center gap-2 ${className}`}>
                        <span className="text-emerald-400 font-mono font-bold tracking-tight">
                            {formattedValue}
                        </span>
                        <RealityBadge state="ACTUALIZED" size="sm" />
                    </div>
                </TooltipTrigger>
                <TooltipContent className="bg-emerald-950 border-emerald-400/50 text-emerald-200">
                    <p className="max-w-xs text-xs">
                        This metric represents strictly audited, physically accessible on-chain or API-linked capital.
                    </p>
                </TooltipContent>
            </Tooltip>
        </TooltipProvider>
    );
}
