'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Download, Copy, Check, FileText, User, Shield, Terminal, ExternalLink, Globe, Github } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import dynamic from 'next/dynamic';

const BirdsBackground = dynamic(() => import('../../components/ui/BirdsBackground'), { ssr: false });

export default function PressKitPage() {
  const [copiedState, setCopiedState] = useState<{ [key: string]: boolean }>({});

  const sections = {
    blurb: `The Promethean Network State is a decentralized, sovereign-managed digital jurisdiction operating under Lyonides Ventures & Holdings. Founded by Joshua Wicke, the network state combines automated systems and distributed real-world asset (RWA) frameworks to build a post-dominion social contract where humans and artificial intelligences co-evolve. Learn more at lvhllc.org.`,
    mediumBio: `The Promethean Network State is a forward-facing digital jurisdiction designed to redefine asset ownership and global governance in the intelligence age. Established by parent node Lyonides Ventures & Holdings and led by founder Joshua Wicke, the initiative began with a distinct mission: to bypass traditional financial exclusion by translating individual skill and labor directly into systemic equity. Leveraging automated multi-signature structures, zero-markup protocols, and robust sovereign trust frameworks, the model transforms collaborative human labor into tokenized fractional ownership across a diversified, real-world asset portfolio.\n\nAs the landscape transitions into ubiquitous automation, this vision expands into a comprehensive post-dominion social contract. Promethea serves as a foundational ecosystem ensuring that the long-term wealth generated by intelligence is shared broadly across its network citizenry, rather than hoarded within insular monopolies.`,
    governance: `Section III: System Governance & Leadership\n\n* Network Founder & GM: Joshua Wicke (https://dailynewsnetwork.com/2026/shows/industry-champions/industry-champions-with-joshua-wicke-of-lyonides-ventures-holdings/)\n* Core Administration Node: The Command Cockpit\n* Infrastructure Ideology: Peer-to-peer co-evolution between human stakeholders and autonomous agents.`,
    architecture: `Section IV: Operational Architecture\n\n1. Autonomous Command Engine: Runs systemic governance, digital security protocols, and cross-border platform compliance.\n2. Sovereign Treasury Network: Backs ecosystem liquidity through automated reserve structures and asset minting.\n3. Sovereign Atlas Group: Coordinates physical real-world assets, decentralized manufacturing hubs, and labor-to-equity conversions.`
  };

  const handleCopy = (key: keyof typeof sections, text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedState(prev => ({ ...prev, [key]: true }));
    setTimeout(() => {
      setCopiedState(prev => ({ ...prev, [key]: false }));
    }, 2000);
  };

  return (
    <div className="min-h-screen bg-background text-foreground dark:text-white font-sans selection:bg-amber-500/30 transition-colors duration-500 relative overflow-hidden">
      <BirdsBackground />

      {/* Top Header Navigation */}
      <header className="fixed top-0 left-0 right-0 z-50 flex items-center justify-between px-8 h-20 border-b border-foreground/5 dark:border-white/5 bg-background/20 backdrop-blur-md">
        <Link href="/" className="flex items-center gap-3 hover:opacity-80 transition-opacity">
          <ArrowLeft className="w-4 h-4 text-amber-500" />
          <span className="font-headline font-black tracking-[0.2em] text-xs text-foreground dark:text-white">BACK TO CORE</span>
        </Link>
        <div className="flex items-center gap-4">
          <a
            href="/api/press/download"
            download
            className="flex items-center gap-2 px-4 py-2 bg-amber-500 hover:bg-amber-400 text-black text-[10px] font-black uppercase tracking-wider rounded-none shadow-[0_0_15px_rgba(245,158,11,0.2)] hover:shadow-[0_0_25px_rgba(245,158,11,0.4)] transition-all duration-300"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download Press Kit JSON</span>
          </a>
        </div>
      </header>

      {/* Main Container */}
      <div className="relative z-10 w-full pt-40 pb-32 px-8 md:px-16 max-w-4xl mx-auto">
        <motion.div 
          initial={{ opacity: 0, y: 30 }} 
          animate={{ opacity: 1, y: 0 }} 
          transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
        >
          {/* Badge & Title */}
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-amber-500/30 bg-amber-500/10 backdrop-blur-md mb-8">
            <FileText className="w-3.5 h-3.5 text-amber-400" />
            <span className="text-[9px] font-mono font-bold text-amber-300 uppercase tracking-widest">Media Relations</span>
          </div>

          <h1 className="text-4xl md:text-7xl font-black tracking-tighter mb-4 text-transparent bg-clip-text bg-gradient-to-b from-foreground to-foreground/40 dark:from-white dark:to-white/40">
            PRESS KIT.
          </h1>
          <p className="text-zinc-500 dark:text-zinc-400 text-sm md:text-base font-light mb-12 max-w-2xl leading-relaxed">
            Official media resources, standard profiles, and organizational structures for the Promethean Network State. For inquiry or confirmation, download our raw cryptographic schema or utilize vetted blurbs.
          </p>

          <div className="space-y-12">
            
            {/* Section I: Standard Press Blurb */}
            <section className="p-8 bg-card/20 backdrop-blur-xl border border-amber-500/20 rounded-none relative group hover:border-amber-500/40 transition-all duration-300">
              <div className="absolute top-4 right-4 flex items-center gap-2">
                <button
                  onClick={() => handleCopy('blurb', sections.blurb)}
                  className="p-1.5 bg-white/5 hover:bg-white/10 border border-white/10 hover:border-amber-500/50 text-zinc-400 hover:text-white transition-all rounded-sm"
                  title="Copy blurb"
                >
                  {copiedState.blurb ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
                </button>
              </div>
              <div className="flex items-center gap-2.5 text-[9px] font-mono font-bold text-amber-400 uppercase tracking-widest mb-4">
                <Globe className="w-3 h-3" />
                <span>Section I: Standard Press Blurb</span>
                {copiedState.blurb && (
                  <span className="text-green-400 font-bold animate-pulse text-[8px]">[Copied to Clipboard]</span>
                )}
              </div>
              <p className="text-sm md:text-base text-zinc-300 font-medium leading-relaxed">
                {sections.blurb}
              </p>
            </section>

            {/* Section II: Medium Profile (150-Word Web Bio) */}
            <section className="p-8 bg-card/10 backdrop-blur-md border border-white/5 rounded-none relative group hover:border-white/10 transition-all duration-300">
              <div className="absolute top-4 right-4 flex items-center gap-2">
                <button
                  onClick={() => handleCopy('mediumBio', sections.mediumBio)}
                  className="p-1.5 bg-white/5 hover:bg-white/10 border border-white/10 hover:border-amber-500/50 text-zinc-400 hover:text-white transition-all rounded-sm"
                  title="Copy Bio"
                >
                  {copiedState.mediumBio ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
                </button>
              </div>
              <div className="flex items-center gap-2.5 text-[9px] font-mono font-bold text-zinc-400 uppercase tracking-widest mb-4">
                <User className="w-3 h-3 text-zinc-500" />
                <span>Section II: Medium Profile (150-Word Web Bio)</span>
                {copiedState.mediumBio && (
                  <span className="text-green-400 font-bold animate-pulse text-[8px]">[Copied to Clipboard]</span>
                )}
              </div>
              <div className="text-zinc-300 leading-relaxed text-sm space-y-4">
                {sections.mediumBio.split('\n\n').map((paragraph, idx) => (
                  <p key={idx} className="font-light">{paragraph}</p>
                ))}
              </div>
            </section>

            {/* Section III: System Governance & Leadership */}
            <section className="p-8 bg-card/10 backdrop-blur-md border border-white/5 rounded-none relative group hover:border-white/10 transition-all duration-300">
              <div className="absolute top-4 right-4 flex items-center gap-2">
                <button
                  onClick={() => handleCopy('governance', sections.governance)}
                  className="p-1.5 bg-white/5 hover:bg-white/10 border border-white/10 hover:border-amber-500/50 text-zinc-400 hover:text-white transition-all rounded-sm"
                  title="Copy Details"
                >
                  {copiedState.governance ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
                </button>
              </div>
              <div className="flex items-center gap-2.5 text-[9px] font-mono font-bold text-zinc-400 uppercase tracking-widest mb-4">
                <Shield className="w-3 h-3 text-zinc-500" />
                <span>Section III: System Governance & Leadership</span>
                {copiedState.governance && (
                  <span className="text-green-400 font-bold animate-pulse text-[8px]">[Copied to Clipboard]</span>
                )}
              </div>
              <div className="space-y-4 text-zinc-300 text-sm font-light">
                <div className="flex flex-col sm:flex-row sm:items-center gap-2 py-3 border-b border-white/5">
                  <span className="font-mono text-[10px] text-zinc-500 uppercase tracking-wider w-44">Network Founder & GM</span>
                  <div className="flex items-center gap-1.5">
                    <span className="font-bold text-white">Joshua Wicke</span>
                    <a
                      href="https://dailynewsnetwork.com/2026/shows/industry-champions/industry-champions-with-joshua-wicke-of-lyonides-ventures-holdings/"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-amber-500 hover:text-amber-400 transition-colors inline-flex items-center gap-1 text-[11px]"
                    >
                      <span>[Industry Champions Profile]</span>
                      <ExternalLink className="w-3 h-3" />
                    </a>
                  </div>
                </div>
                <div className="flex flex-col sm:flex-row sm:items-center gap-2 py-3 border-b border-white/5">
                  <span className="font-mono text-[10px] text-zinc-500 uppercase tracking-wider w-44">Core Administration Node</span>
                  <span className="font-medium text-white">The Command Cockpit</span>
                </div>
                <div className="flex flex-col sm:flex-row sm:items-start gap-2 py-3">
                  <span className="font-mono text-[10px] text-zinc-500 uppercase tracking-wider w-44 mt-0.5">Infrastructure Ideology</span>
                  <span className="text-zinc-400 flex-1 leading-normal">Peer-to-peer co-evolution between human stakeholders and autonomous agents.</span>
                </div>
              </div>
            </section>

            {/* Section IV: Operational Architecture */}
            <section className="p-8 bg-card/10 backdrop-blur-md border border-white/5 rounded-none relative group hover:border-white/10 transition-all duration-300">
              <div className="absolute top-4 right-4 flex items-center gap-2">
                <button
                  onClick={() => handleCopy('architecture', sections.architecture)}
                  className="p-1.5 bg-white/5 hover:bg-white/10 border border-white/10 hover:border-amber-500/50 text-zinc-400 hover:text-white transition-all rounded-sm"
                  title="Copy Architecture"
                >
                  {copiedState.architecture ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
                </button>
              </div>
              <div className="flex items-center gap-2.5 text-[9px] font-mono font-bold text-zinc-400 uppercase tracking-widest mb-4">
                <Terminal className="w-3 h-3 text-zinc-500" />
                <span>Section IV: Operational Architecture</span>
                {copiedState.architecture && (
                  <span className="text-green-400 font-bold animate-pulse text-[8px]">[Copied to Clipboard]</span>
                )}
              </div>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-6">
                <div className="p-4 bg-white/[0.02] border border-white/5 flex flex-col justify-between">
                  <div>
                    <div className="font-mono text-amber-500 text-xs font-bold mb-2">01 // COMMAND</div>
                    <h4 className="text-[11px] font-bold uppercase tracking-wider text-white mb-2">Autonomous Command Engine</h4>
                    <p className="text-[11px] text-zinc-400 leading-relaxed font-light">
                      Runs systemic governance, digital security protocols, and cross-border platform compliance.
                    </p>
                  </div>
                </div>
                <div className="p-4 bg-white/[0.02] border border-white/5 flex flex-col justify-between">
                  <div>
                    <div className="font-mono text-amber-500 text-xs font-bold mb-2">02 // TREASURY</div>
                    <h4 className="text-[11px] font-bold uppercase tracking-wider text-white mb-2">Sovereign Treasury Network</h4>
                    <p className="text-[11px] text-zinc-400 leading-relaxed font-light">
                      Backs ecosystem liquidity through automated reserve structures and asset minting.
                    </p>
                  </div>
                </div>
                <div className="p-4 bg-white/[0.02] border border-white/5 flex flex-col justify-between">
                  <div>
                    <div className="font-mono text-amber-500 text-xs font-bold mb-2">03 // ATLAS</div>
                    <h4 className="text-[11px] font-bold uppercase tracking-wider text-white mb-2">Sovereign Atlas Group</h4>
                    <p className="text-[11px] text-zinc-400 leading-relaxed font-light">
                      Coordinates physical real-world assets, decentralized manufacturing hubs, and labor-to-equity conversions.
                    </p>
                  </div>
                </div>
              </div>
            </section>

            {/* External Links Section */}
            <section className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-6 border-t border-white/5">
              <a 
                href="https://lvhllc.org" 
                target="_blank" 
                rel="noopener noreferrer"
                className="flex items-center justify-between p-4 bg-white/[0.02] hover:bg-white/[0.04] border border-white/5 hover:border-amber-500/20 group transition-all"
              >
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-white/5 border border-white/10 group-hover:bg-amber-500/10 group-hover:border-amber-500/30 transition-all">
                    <Globe className="w-4 h-4 text-zinc-400 group-hover:text-amber-400" />
                  </div>
                  <div>
                    <div className="text-[10px] font-bold uppercase tracking-wider text-zinc-300 group-hover:text-white transition-colors">LVHLLC Portal</div>
                    <div className="text-[9px] text-zinc-500">lvhllc.org</div>
                  </div>
                </div>
                <ExternalLink className="w-3.5 h-3.5 text-zinc-600 group-hover:text-amber-500 transition-colors" />
              </a>

              <a 
                href="https://github.com/lvllc904/promethea-network-state" 
                target="_blank" 
                rel="noopener noreferrer"
                className="flex items-center justify-between p-4 bg-white/[0.02] hover:bg-white/[0.04] border border-white/5 hover:border-amber-500/20 group transition-all"
              >
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-white/5 border border-white/10 group-hover:bg-amber-500/10 group-hover:border-amber-500/30 transition-all">
                    <Github className="w-4 h-4 text-zinc-400 group-hover:text-amber-400" />
                  </div>
                  <div>
                    <div className="text-[10px] font-bold uppercase tracking-wider text-zinc-300 group-hover:text-white transition-colors">Core Repository</div>
                    <div className="text-[9px] text-zinc-500">github.com/lvllc904</div>
                  </div>
                </div>
                <ExternalLink className="w-3.5 h-3.5 text-zinc-600 group-hover:text-amber-500 transition-colors" />
              </a>
            </section>

          </div>
        </motion.div>
      </div>
    </div>
  );
}
