"""Create master data tables

Revision ID: 1d79bbf6ae7a
Revises: 
Create Date: 2025-09-27 18:28:37.138364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d79bbf6ae7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('economic_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_name', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('update_interval_hours', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economic_indicators_id'), 'economic_indicators', ['id'], unique=False)
    op.create_index(op.f('ix_economic_indicators_indicator_name'), 'economic_indicators', ['indicator_name'], unique=True)
    op.create_table('portfolio_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_history_id'), 'portfolio_history', ['id'], unique=False)
    op.create_table('tradable_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('asset_class', sa.Enum('CRYPTO', 'US_EQUITY', name='assetclass'), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tradable_assets_id'), 'tradable_assets', ['id'], unique=False)
    op.create_index(op.f('ix_tradable_assets_name'), 'tradable_assets', ['name'], unique=True)
    op.create_index(op.f('ix_tradable_assets_symbol'), 'tradable_assets', ['symbol'], unique=True)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('trade_type', sa.Enum('BUY', 'SELL', name='tradetype'), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_asset_id'), 'trades', ['asset_id'], unique=False)
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_asset_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_tradable_assets_symbol'), table_name='tradable_assets')
    op.drop_index(op.f('ix_tradable_assets_name'), table_name='tradable_assets')
    op.drop_index(op.f('ix_tradable_assets_id'), table_name='tradable_assets')
    op.drop_table('tradable_assets')
    op.drop_index(op.f('ix_portfolio_history_id'), table_name='portfolio_history')
    op.drop_table('portfolio_history')
    op.drop_index(op.f('ix_economic_indicators_indicator_name'), table_name='economic_indicators')
    op.drop_index(op.f('ix_economic_indicators_id'), table_name='economic_indicators')
    op.drop_table('economic_indicators')
    # ### end Alembic commands ###
