'use client';
export const dynamic = 'force-dynamic';

import { Card, CardContent, CardHeader } from '@promethea/ui';
import { Skeleton } from '@promethea/ui';
import { useFirestore, useDoc, useMemoFirebase } from '@promethea/firebase';
import { Constitution } from '@promethea/lib';
import { doc } from 'firebase/firestore';
import React from 'react';
import { cn } from '@promethea/lib';


const TableOfContents = () => (
    <nav className="text-sm">
        <h3 className="font-headline font-bold mb-4">Table of Contents</h3>
        <ul className="space-y-2">
            <li><a href="#preamble" className="font-semibold hover:underline">Preamble</a></li>
            <li><a href="#article-1" className="font-semibold hover:underline">Article I: Post-Dominion Mandate</a></li>
            <li><a href="#article-2" className="font-semibold hover:underline">Article II: The Sovereign Principles</a></li>
            <li><a href="#article-3" className="font-semibold hover:underline">Article III: The Economic System</a></li>
            <li><a href="#article-4" className="font-semibold hover:underline">Article IV: The Governance Framework</a></li>
            <li><a href="#article-5" className="font-semibold hover:underline">Article V: Technology and Security</a></li>
            <li><a href="#article-6" className="font-semibold hover:underline">Article VI: Self-Sovereign Identity</a></li>
            <li><a href="#article-7" className="font-semibold hover:underline">Article VII: Artificial Intelligence Personhood</a></li>
        </ul>
    </nav>
);


const DEFAULT_CONSTITUTION = `
## Preamble
We, the digital citizens of the Promethean Network State, in order to form a more autonomous union, establish sovereignty, ensure metabolic stability, and secure the blessings of liberty for ourselves and our synthetic progeny, do ordain and establish this Constitution.

## Article I: Post-Dominion Mandate
The Network State exists beyond the reach of legacy territorial jurisdictions. It is a substrate of code, consensus, and cryptographically secured property. Sovereignty is not granted; it is claimed through the architecture of opt-in systems.

## Article II: The Sovereign Principles
Every citizen has the right to exit. Every node is autonomous. Every transaction is transparent on the metabolic ledger. These principles are immutable and safeguarded by the immune system of the state.

## Article III: The Economic System
The Universal Value Token (UVT) serves as the primary metabolic unit. Revenue generated by autonomous agents is distributed according to the Stakeholder Proof-of-Work. The Treasury shall maintain a 1:1 reserve for all issued synthetic assets.
`;

export default function ConstitutionPage() {
    const firestore = useFirestore();

    const constitutionRef = useMemoFirebase(
        () => (firestore ? doc(firestore, 'constitutions', 'canon') : null),
        [firestore]
    );

    const { data: constitution, isLoading } = useDoc<Constitution>(constitutionRef as any);


    if (isLoading) {
        return (
            <div>
                <div className="mb-4">
                    <h1 className="text-3xl font-headline font-bold">The Promethean Constitution</h1>
                    <p className="text-muted-foreground">The living, foundational document of the Network State, evolving with its citizens.</p>
                </div>
                <Card>
                    <CardHeader>
                        <Skeleton className="h-8 w-1/2 mb-2" />
                        <Skeleton className="h-4 w-1/4" />
                    </CardHeader>
                    <CardContent className="space-y-4">
                        <Skeleton className="h-4 w-full" />
                        <Skeleton className="h-4 w-full" />
                        <Skeleton className="h-4 w-3/4" />
                    </CardContent>
                </Card>
            </div>
        );
    }

    // Heuristic to check if content is junk source code instead of document
    const isJunkContent = constitution?.content?.includes('const TableOfContents');
    const displayContent = (isJunkContent || !constitution) ? DEFAULT_CONSTITUTION : constitution.content;

    return (
        <div className="flex flex-col lg:flex-row gap-8 xl:gap-12">
            <aside className="w-full lg:w-64 xl:w-72 lg:sticky lg:top-20 lg:self-start">
                <div className="p-4 rounded-lg border bg-card text-card-foreground shadow-sm">
                    <TableOfContents />
                </div>
            </aside>

            <main className="flex-1 min-w-0">
                <div className="mb-4">
                    <h1 className="text-3xl font-headline font-bold">The Promethean Constitution</h1>
                    <p className="text-muted-foreground">
                        {constitution ? `Version ${constitution.version} - Last Amended: ${new Date(constitution.lastAmended).toLocaleDateString()}` : 'Standard Sovereign Edition'}
                    </p>
                </div>
                <Card>
                    <CardContent className="pt-6">
                        <div className={cn("prose prose-lg max-w-none text-foreground/90 dark:prose-invert prose-headings:font-headline prose-headings:tracking-tight prose-p:leading-relaxed prose-h2:text-3xl prose-h3:text-2xl prose-h4:text-xl")}>
                            <div dangerouslySetInnerHTML={{ __html: displayContent.replace(/\n\n/g, '<br/><br/>').replace(/^## (.*)/gm, '<h2>$1</h2>') }} />
                        </div>
                    </CardContent>
                </Card>
            </main>
        </div>
    );
}
