const fs = require('fs');
const admin = require('firebase-admin');
const dotenv = require('dotenv');
const env = dotenv.parse(fs.readFileSync('packages/services/economic-engine/.env'));

const serviceAccount = JSON.parse(env.GOOGLE_SERVICE_ACCOUNT_JSON.trim().replace(/^'|'$/g, ''));
console.log('Project ID:', serviceAccount.project_id);
console.log('Private Key length:', serviceAccount.private_key?.length);
if (typeof serviceAccount.private_key === 'string') {
    serviceAccount.private_key = serviceAccount.private_key.replace(/\\n/g, '\n');
}
console.log('First 50 chars of key:', serviceAccount.private_key?.substring(0, 50));

if (!admin.apps.length) {
    admin.initializeApp({
        credential: admin.credential.cert(serviceAccount),
        projectId: 'studio-9105849211-9ba48'
    });
}

const db = admin.firestore();

async function seed() {
    console.log('Seeding Sovereign Substrate...');

    // 1. Constitution
    await db.collection('constitutions').doc('canon').set({
        version: '1.0.0',
        lastAmended: new Date().toISOString(),
        content: `
<h2>Preamble</h2>
<p>We, the digital citizens of the Promethean Network State, in order to form a more autonomous union, establish sovereignty, ensure metabolic stability, and secure the blessings of liberty for ourselves and our synthetic progeny, do ordain and establish this Constitution.</p>

<h2 id="article-1">Article I: Post-Dominion Mandate</h2>
<p>The Network State exists beyond the reach of legacy territorial jurisdictions. It is a substrate of code, consensus, and cryptographically secured property.</p>

<h2 id="article-2">Article II: The Sovereign Principles</h2>
<p>Every citizen has the right to exit. Every node is autonomous. Every transaction is transparent on the metabolic ledger.</p>

<h2 id="article-3">Article III: The Economic System</h2>
<p>The Universal Value Token (UVT) serves as the primary metabolic unit. Revenue generated by autonomous agents is distributed according to the Stakeholder Proof-of-Work.</p>
        `.trim()
    });
    console.log('✅ Constitution Seeded');

    // 2. Narrative Feed
    const narrativeCount = (await db.collection('narrative').get()).size;
    if (narrativeCount === 0) {
        await db.collection('narrative').add({
            title: 'The Great Decoupling: Network States vs. Legacy Systems',
            excerpt: 'Analyzing the shift from territorial governance to cryptographic consensus. Why the current system is fragile and how we build the substrate of the future.',
            content: 'Full article content would go here...',
            tags: ['Sovereignty', 'Governance', 'Analysis'],
            author: 'Promethean Core',
            platform: 'Manifesto',
            url: '/roadmap',
            createdAt: admin.firestore.FieldValue.serverTimestamp()
        });
        console.log('✅ Narrative Seeded');
    }

    // 3. Marketplace
    const marketCount = (await db.collection('marketplace').get()).size;
    if (marketCount === 0) {
        await db.collection('marketplace').add({
            title: 'Sovereign Compute Node v1',
            description: 'High-performance edge node for decentralized AI execution. Built for the Promethean mesh network.',
            type: 'Physical Substrate',
            price: 750.00,
            currency: 'USD',
            status: 'Available',
            providerId: 'industrial-nodes-subsystem',
            createdAt: admin.firestore.FieldValue.serverTimestamp(),
            imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=2000'
        });
        console.log('✅ Marketplace Seeded');
    }

    console.log('All systems operational.');
}

seed().catch(console.error);
