
import firebase_admin
from firebase_admin import credentials, firestore
import json
import os

def seed():
    # Path to the .env file
    env_path = 'packages/services/economic-engine/.env'
    
    # Simple .env parser
    env_data = {}
    with open(env_path, 'r') as f:
        for line in f:
            if '=' in line:
                key, value = line.strip().split('=', 1)
                env_data[key] = value

    sa_json_str = env_data.get('GOOGLE_SERVICE_ACCOUNT_JSON', '').strip().strip("'")
    if not sa_json_str:
        print("Error: GOOGLE_SERVICE_ACCOUNT_JSON not found in .env")
        return

    sa_info = json.loads(sa_json_str)
    # The private key might have double-escaped newlines
    sa_info['private_key'] = sa_info['private_key'].replace('\\n', '\n')

    cred = credentials.Certificate(sa_info)
    firebase_admin.initialize_app(cred, {
        'projectId': 'studio-9105849211-9ba48'
    })

    db = firestore.client()

    print("Restoring Constitution...")
    constitution_content = """
<h2>Preamble</h2>
<p>We, the digital citizens of the Promethean Network State, in order to form a more autonomous union, establish sovereignty, ensure metabolic stability, and secure the blessings of liberty for ourselves and our synthetic progeny, do ordain and establish this Constitution.</p>

<h2 id="article-1">Article I: Post-Dominion Mandate</h2>
<p>The Network State exists beyond the reach of legacy territorial jurisdictions. It is a substrate of code, consensus, and cryptographically secured property. Sovereignty is not granted; it is claimed through the architecture of opt-in systems.</p>

<h2 id="article-2">Article II: The Sovereign Principles</h2>
<p>Every citizen has the right to exit. Every node is autonomous. Every transaction is transparent on the metabolic ledger. These principles are immutable and safeguarded by the immune system of the state.</p>

<h2 id="article-3">Article III: The Economic System</h2>
<p>The Universal Value Token (UVT) serves as the primary metabolic unit. Revenue generated by autonomous agents is distributed according to the Stakeholder Proof-of-Work. The Treasury shall maintain a 1:1 reserve for all issued synthetic assets.</p>

<h2 id="article-4">Article IV: The Governance Framework</h2>
<p>Governance is executed via Quadratic Voting and weighted consensus. Proposals must undergo a period of discussion before being committed to the chain of execution.</p>
    """

    db.collection('constitutions').document('canon').set({
        'version': '1.0.1',
        'lastAmended': firestore.SERVER_TIMESTAMP,
        'content': constitution_content.strip()
    })
    print("✅ Constitution Restored.")

    # Narrative
    print("Checking Narrative...")
    narrative_col = db.collection('narrative')
    if len(list(narrative_col.limit(1).get())) == 0:
        narrative_col.add({
            'title': 'The Sovereign Shift',
            'excerpt': 'As legacy nation-states struggle with centralization, the Network State emerges as a modular, opt-in alternative. Built on the substrate of cryptography.',
            'content': 'Transmitting now...',
            'tags': ['Sovereignty', 'Future', 'Transmissions'],
            'author': 'Promethea',
            'platform': 'Manifesto',
            'createdAt': firestore.SERVER_TIMESTAMP
        })
        print("✅ Narrative Seeded.")

if __name__ == "__main__":
    seed()
