import { db, COLLECTIONS } from '../db';
import { personaSubstrate } from '../tools/persona-substrate';

/**
 * Sovereign Marketplace Service (Phase 3.5)
 * 
 * Manages the distribution and sale of autonomous engine outputs.
 */

export interface MarketplaceItem {
    id?: string;
    title: string;
    description: string;
    type: 'Digital' | 'Physical' | 'Service';
    price: number;
    currency: 'USD' | 'UVT' | 'SOL';
    methodId: string;
    imageUrl?: string;
    metadata?: Record<string, any>;
    status: 'Available' | 'Sold' | 'Archived' | 'TradeProposed';
    barterAllowed: boolean;
    barterPreferences?: string;
    uvxType?: 'TFC' | 'CPT' | 'STANDARD';
    tier?: 'AAA' | 'A' | 'B' | 'D';
    maturityDate?: any;
    expirationDate?: any;
    isPerishable?: boolean;
    collateralBond?: number;
    providerId: string;
    createdAt: any;
}

export class MarketplaceService {
    /**
     * List a new item generated by an economic method
     */
    async listItem(item: Omit<MarketplaceItem, 'createdAt' | 'status'>): Promise<string> {
        const itemRef = await db.collection('marketplace').add({
            ...item,
            status: 'Available',
            createdAt: new Date().toISOString()
        });

        console.log(`[Marketplace] New item listed: ${item.title} ($${item.price})`);
        return itemRef.id;
    }

    /**
     * Mark an item as sold
     */
    async markAsSold(itemId: string): Promise<void> {
        await db.collection('marketplace').doc(itemId).update({
            status: 'Sold',
            soldAt: new Date().toISOString()
        });
    }

    /**
     * Propose a barter trade for an item
     */
    async proposeBarter(itemId: string, offer: string, proposerId: string): Promise<void> {
        await db.collection('marketplace').doc(itemId).collection('trades').add({
            proposerId,
            offer,
            status: 'Pending',
            createdAt: new Date().toISOString()
        });

        await db.collection('marketplace').doc(itemId).update({
            status: 'TradeProposed'
        });

        console.log(`[Marketplace] New trade proposed for item ${itemId} by ${proposerId}`);
    }

    /**
     * One-Click Ingestion: Parses a raw proposal and lists it as a UVX Asset
     */
    async ingestProposal(proposalText: string, providerId: string, genAI: any): Promise<string> {
        console.log(`[Marketplace] AI Ingestion triggered for provider: ${providerId}`);

        const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
        const prompt = `
        Analyze the following Barter/Investment Proposal and extract a structured Sovereign Marketplace Listing.
        Proposal: "${proposalText}"
        
        Identify:
        1. Title & Description
        2. UVX Type (TFC: Future Credit, CPT: Perishable Capacity, STANDARD: Item)
        3. Valuation (USD/UVT)
        4. Expiry/Maturity (if applicable)
        5. Barter Preferences
        6. Asset Category (One of: RESTORATION_LAND, MINERAL_CLAIM, RECLAMATION_BROWNFIELD, DEPIN_COMPUTE, COMPUTE_NODE, STANDARD)
        
        Return valid JSON:
        {
            "title": "...",
            "description": "...",
            "type": "Digital/Physical/Service",
            "price": number,
            "currency": "USD",
            "uvxType": "TFC/CPT/STANDARD",
            "isPerishable": boolean,
            "barterAllowed": true,
            "barterPreferences": "...",
            "assetType": "RESTORATION_LAND/MINERAL_CLAIM/DEPIN_COMPUTE/etc"
        }
        `;

        const result = await model.generateContent(prompt);
        const text = result.response.text();
        const jsonStr = text.replace(/```json/g, '').replace(/```/g, '').trim();
        const data = JSON.parse(jsonStr);

        const assetId = 'asset-' + Date.now();
        const assetData = {
            id: assetId,
            name: data.title,
            title: data.title,
            description: data.description,
            price: data.price,
            currency: data.currency || 'USD',
            assetType: data.assetType || 'RESTORATION_LAND',
            status: 'Idea',
            realityState: 'SIMULATED',
            progressionState: 'IDEA',
            prerequisiteTasks: [],
            providerId,
            methodId: 'ai-ingestion',
            createdAt: new Date().toISOString()
        };

        // Write to real_world_assets collection
        await db.collection('real_world_assets').doc(assetId).set(assetData);

        // Generate prerequisite quests
        const { metabolicTaskGenerator } = require('./metabolic-task-generator');
        await metabolicTaskGenerator.generatePrerequisiteQuests(assetId, data.title, data.assetType || 'RESTORATION_LAND');

        return assetId;
    }

    /**
     * Transition the progressive actualization state of an asset
     */
    async transitionState(assetId: string, targetState: string): Promise<void> {
        const assetRef = db.collection('real_world_assets').doc(assetId);
        const doc = await assetRef.get();
        if (!doc.exists) throw new Error('Asset not found');

        const asset = doc.data();
        const currentState = asset.progressionState || 'IDEA';
        console.log(`[MarketplaceService] 🔄 Checking manual state transition of ${asset.name} from ${currentState} to ${targetState}`);

        // Validate targetState
        const validStates = ['IDEA', 'VETTED', 'LEGALIZED', 'SECURED', 'ACTUALIZED'];
        if (!validStates.includes(targetState)) {
            throw new Error(`Invalid target state: ${targetState}`);
        }

        // Run transition-specific checks
        if (targetState === 'VETTED') {
            const yesVotes = asset.yesVotes || 0;
            const noVotes = asset.noVotes || 0;
            if (yesVotes - noVotes < 10) {
                throw new Error('Asset requires at least +10 net consensus votes to progress to VETTED state.');
            }
        } else if (targetState === 'LEGALIZED') {
            // Find Legal quest
            const questsSnapshot = await db.collection('quests').get();
            const legalQuest = questsSnapshot.docs
                .map((d: any) => d.data())
                .find((q: any) => q.associatedAssetId === assetId && q.questType === 'Legal');
            if (!legalQuest || legalQuest.status !== 'COMPLETED') {
                throw new Error('Asset requires Wyoming DUNA Operating Agreement / Entity Wrapping to be completed.');
            }
        } else if (targetState === 'SECURED') {
            const hasUcc1Filing = asset.ucc1FilingId || asset.bypassReceiptUrl || asset.wyomingFilingNumber;
            const questsSnapshot = await db.collection('quests').get();
            const financialQuest = questsSnapshot.docs
                .map((d: any) => d.data())
                .find((q: any) => q.associatedAssetId === assetId && q.questType === 'Financial');
            const financialDone = financialQuest && financialQuest.status === 'COMPLETED';

            if (!financialDone && !hasUcc1Filing) {
                throw new Error('Asset requires Secretary of State filing fee or UCC-1 Filing registration / Bypass Upload.');
            }
        } else if (targetState === 'ACTUALIZED') {
            const questsSnapshot = await db.collection('quests').get();
            const assetQuests = questsSnapshot.docs
                .map((d: any) => d.data())
                .filter((q: any) => q.associatedAssetId === assetId);

            const physicalQuest = assetQuests.find((q: any) => q.questType === 'Physical');
            const techQuest = assetQuests.find((q: any) => q.questType === 'Technical');
            
            const physicalDone = !physicalQuest || physicalQuest.status === 'COMPLETED';
            const techDone = !techQuest || techQuest.status === 'COMPLETED';

            if (!physicalDone || !techDone) {
                throw new Error('Asset requires all physical and technical boundary telemetry quests to be completed before actualizing.');
            }

            // Perform token minting loop if actualized
            await assetRef.update({
                realityState: 'ACTUALIZED',
                status: 'Active'
            });
        }

        await assetRef.update({
            progressionState: targetState
        });

        await personaSubstrate.broadcastUpdate(
            `State Transition: ${asset.name}`,
            `${asset.name} has been transitioned to ${targetState}.`,
            assetId
        );
    }
    /**
     * ATOMIC ASSET SWAP (Wave 10)
     * 
     * Executes a one-click settlement where UVT is transferred from the buyer 
     * and the asset is marked as Sold/Actualized.
     */
    async executeAtomicSwap(itemId: string, buyerDid: string, buyerWallet: string): Promise<string> {
        const { walletManager } = require('../treasury/wallet-manager');
        const { reserveManager } = require('../treasury/reserve-manager');

        const doc = await db.collection('marketplace').doc(itemId).get();
        if (!doc.exists) throw new Error('Marketplace item not found');

        const item = doc.data() as MarketplaceItem;
        const mintAddress = process.env.UVT_MINT_ADDRESS || 'Bm2GRKS92odxL6P4grmYyDMNChWNhQPHrLgcJRab7vf1';

        console.log(`[Exchange] 🏛️  Initiating Atomic Swap for ${item.title} ($${item.price})`);

        // 1. Bonded Escrow Check (Phase 10.2)
        if (item.collateralBond && item.collateralBond > 0) {
            console.log(`[Exchange] 🛡️  Verifying Bonded Escrow: $${item.collateralBond} required.`);
            // In production, we would check the buyer's reputation score or staked UVT.
        }

        try {
            // 2. Execute UVT Transfer (The Payment)
            // Note: In this simulation, the engine facilitates the transfer via the master key 
            // if authorized by the 3-Body handshake.
            const sig = await walletManager.transferSPL(
                mintAddress, 
                item.providerId, // Seller's address
                item.price,
                9
            );

            // 3. Update Ledger
            await this.markAsSold(itemId);

            // 4. Trigger Waterfall Synthesis (Plowback)
            reserveManager.onProfitRealized(item.price);

            console.log(`[Exchange] ✅ Atomic Swap Complete. TX: ${sig}`);

            await personaSubstrate.broadcastUpdate(
                'Sovereign Exchange: Atomic Swap Success',
                `${buyerDid} has acquired ${item.title} for ${item.price} UVT.`,
                itemId
            );

            return sig;
        } catch (e) {
            console.error(`[Exchange] ❌ Atomic Swap Failed:`, e);
            throw e;
        }
    }
}

export const marketplaceService = new MarketplaceService();
