import { db, COLLECTIONS } from '../db';
import * as admin from 'firebase-admin';

/**
 * Sovereign Marketplace Service (Phase 3.5)
 * 
 * Manages the distribution and sale of autonomous engine outputs.
 */

export interface MarketplaceItem {
    id?: string;
    title: string;
    description: string;
    type: 'Digital' | 'Physical' | 'Service';
    price: number;
    currency: 'USD' | 'UVT' | 'SOL';
    methodId: string;
    imageUrl?: string;
    metadata?: Record<string, any>;
    status: 'Available' | 'Sold' | 'Archived' | 'TradeProposed';
    barterAllowed: boolean;
    barterPreferences?: string;
    uvxType?: 'TFC' | 'CPT' | 'STANDARD';
    tier?: 'AAA' | 'A' | 'B' | 'D';
    maturityDate?: any;
    expirationDate?: any;
    isPerishable?: boolean;
    collateralBond?: number;
    providerId: string;
    createdAt: any;
}

export class MarketplaceService {
    /**
     * List a new item generated by an economic method
     */
    async listItem(item: Omit<MarketplaceItem, 'createdAt' | 'status'>): Promise<string> {
        const itemRef = await db.collection('marketplace').add({
            ...item,
            status: 'Available',
            createdAt: admin.firestore.FieldValue.serverTimestamp()
        });

        console.log(`[Marketplace] New item listed: ${item.title} ($${item.price})`);
        return itemRef.id;
    }

    /**
     * Mark an item as sold
     */
    async markAsSold(itemId: string): Promise<void> {
        await db.collection('marketplace').doc(itemId).update({
            status: 'Sold',
            soldAt: admin.firestore.FieldValue.serverTimestamp()
        });
    }

    /**
     * Propose a barter trade for an item
     */
    async proposeBarter(itemId: string, offer: string, proposerId: string): Promise<void> {
        await db.collection('marketplace').doc(itemId).collection('trades').add({
            proposerId,
            offer,
            status: 'Pending',
            createdAt: admin.firestore.FieldValue.serverTimestamp()
        });

        await db.collection('marketplace').doc(itemId).update({
            status: 'TradeProposed'
        });

        console.log(`[Marketplace] New trade proposed for item ${itemId} by ${proposerId}`);
    }

    /**
     * One-Click Ingestion: Parses a raw proposal and lists it as a UVX Asset
     */
    async ingestProposal(proposalText: string, providerId: string, genAI: any): Promise<string> {
        console.log(`[Marketplace] AI Ingestion triggered for provider: ${providerId}`);

        const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });
        const prompt = `
        Analyze the following Barter/Investment Proposal and extract a structured Sovereign Marketplace Listing.
        Proposal: "${proposalText}"
        
        Identify:
        1. Title & Description
        2. UVX Type (TFC: Future Credit, CPT: Perishable Capacity, STANDARD: Item)
        3. Valuation (USD/UVT)
        4. Expiry/Maturity (if applicable)
        5. Barter Preferences
        
        Return valid JSON:
        {
            "title": "...",
            "description": "...",
            "type": "Digital/Physical/Service",
            "price": number,
            "currency": "USD",
            "uvxType": "TFC/CPT/STANDARD",
            "isPerishable": boolean,
            "barterAllowed": true,
            "barterPreferences": "..."
        }
        `;

        const result = await model.generateContent(prompt);
        const text = result.response.text();
        const jsonStr = text.replace(/```json/g, '').replace(/```/g, '').trim();
        const data = JSON.parse(jsonStr);

        return this.listItem({
            ...data,
            providerId,
            methodId: 'ai-ingestion'
        });
    }
}

export const marketplaceService = new MarketplaceService();
