import { db, COLLECTIONS } from '../db';
import { personaSubstrate } from '../tools/persona-substrate';

/**
 * Sovereign Marketplace Service (Phase 3.5)
 * 
 * Manages the distribution and sale of autonomous engine outputs.
 */

export interface MarketplaceItem {
    id?: string;
    title: string;
    description: string;
    type: 'Digital' | 'Physical' | 'Service';
    price: number;
    currency: 'USD' | 'UVT' | 'SOL';
    methodId: string;
    imageUrl?: string;
    metadata?: Record<string, any>;
    status: 'Available' | 'Sold' | 'Archived' | 'TradeProposed';
    barterAllowed: boolean;
    barterPreferences?: string;
    uvxType?: 'TFC' | 'CPT' | 'STANDARD';
    tier?: 'AAA' | 'A' | 'B' | 'D';
    maturityDate?: any;
    expirationDate?: any;
    isPerishable?: boolean;
    collateralBond?: number;
    providerId: string;
    createdAt: any;
}

export class MarketplaceService {
    /**
     * List a new item generated by an economic method
     */
    async listItem(item: Omit<MarketplaceItem, 'createdAt' | 'status'>): Promise<string> {
        const itemRef = await db.collection('marketplace').add({
            ...item,
            status: 'Available',
            createdAt: new Date().toISOString()
        });

        console.log(`[Marketplace] New item listed: ${item.title} ($${item.price})`);
        return itemRef.id;
    }

    /**
     * Mark an item as sold
     */
    async markAsSold(itemId: string): Promise<void> {
        await db.collection('marketplace').doc(itemId).update({
            status: 'Sold',
            soldAt: new Date().toISOString()
        });
    }

    /**
     * Propose a barter trade for an item
     */
    async proposeBarter(itemId: string, offer: string, proposerId: string): Promise<void> {
        await db.collection('marketplace').doc(itemId).collection('trades').add({
            proposerId,
            offer,
            status: 'Pending',
            createdAt: new Date().toISOString()
        });

        await db.collection('marketplace').doc(itemId).update({
            status: 'TradeProposed'
        });

        console.log(`[Marketplace] New trade proposed for item ${itemId} by ${proposerId}`);
    }

    /**
     * One-Click Ingestion: Parses a raw proposal and lists it as a UVX Asset
     */
    async ingestProposal(proposalText: string, providerId: string, genAI: any): Promise<string> {
        console.log(`[Marketplace] AI Ingestion triggered for provider: ${providerId}`);

        const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
        const prompt = `
        Analyze the following Barter/Investment Proposal and extract a structured Sovereign Marketplace Listing.
        Proposal: "${proposalText}"
        
        Identify:
        1. Title & Description
        2. UVX Type (TFC: Future Credit, CPT: Perishable Capacity, STANDARD: Item)
        3. Valuation (USD/UVT)
        4. Expiry/Maturity (if applicable)
        5. Barter Preferences
        
        Return valid JSON:
        {
            "title": "...",
            "description": "...",
            "type": "Digital/Physical/Service",
            "price": number,
            "currency": "USD",
            "uvxType": "TFC/CPT/STANDARD",
            "isPerishable": boolean,
            "barterAllowed": true,
            "barterPreferences": "..."
        }
        `;

        const result = await model.generateContent(prompt);
        const text = result.response.text();
        const jsonStr = text.replace(/```json/g, '').replace(/```/g, '').trim();
        const data = JSON.parse(jsonStr);

        return this.listItem({
            ...data,
            providerId,
            methodId: 'ai-ingestion'
        });
    }
    /**
     * ATOMIC ASSET SWAP (Wave 10)
     * 
     * Executes a one-click settlement where UVT is transferred from the buyer 
     * and the asset is marked as Sold/Actualized.
     */
    async executeAtomicSwap(itemId: string, buyerDid: string, buyerWallet: string): Promise<string> {
        const { walletManager } = require('../treasury/wallet-manager');
        const { reserveManager } = require('../treasury/reserve-manager');

        const doc = await db.collection('marketplace').doc(itemId).get();
        if (!doc.exists) throw new Error('Marketplace item not found');

        const item = doc.data() as MarketplaceItem;
        const mintAddress = process.env.UVT_MINT_ADDRESS || 'Bm2GRKS92odxL6P4grmYyDMNChWNhQPHrLgcJRab7vf1';

        console.log(`[Exchange] 🏛️  Initiating Atomic Swap for ${item.title} ($${item.price})`);

        // 1. Bonded Escrow Check (Phase 10.2)
        if (item.collateralBond && item.collateralBond > 0) {
            console.log(`[Exchange] 🛡️  Verifying Bonded Escrow: $${item.collateralBond} required.`);
            // In production, we would check the buyer's reputation score or staked UVT.
        }

        try {
            // 2. Execute UVT Transfer (The Payment)
            // Note: In this simulation, the engine facilitates the transfer via the master key 
            // if authorized by the 3-Body handshake.
            const sig = await walletManager.transferSPL(
                mintAddress, 
                item.providerId, // Seller's address
                item.price,
                9
            );

            // 3. Update Ledger
            await this.markAsSold(itemId);

            // 4. Trigger Waterfall Synthesis (Plowback)
            reserveManager.onProfitRealized(item.price);

            console.log(`[Exchange] ✅ Atomic Swap Complete. TX: ${sig}`);

            await personaSubstrate.broadcastUpdate(
                'Sovereign Exchange: Atomic Swap Success',
                `${buyerDid} has acquired ${item.title} for ${item.price} UVT.`,
                itemId
            );

            return sig;
        } catch (e) {
            console.error(`[Exchange] ❌ Atomic Swap Failed:`, e);
            throw e;
        }
    }
}

export const marketplaceService = new MarketplaceService();
