"""Create initial databse schema

Revision ID: b560114ca220
Revises: 
Create Date: 2025-09-20 19:32:25.160162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b560114ca220'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asset_symbol', sa.String(length=255), nullable=False),
    sa.Column('asset_class', sa.String(length=50), nullable=False),
    sa.Column('asset_adapter', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_tradable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_symbol')
    )
    op.create_table('agent_configurations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('world_model_weights_path', sa.String(length=1024), nullable=False),
    sa.Column('rollout_policy_path', sa.String(length=1024), nullable=True),
    sa.Column('mcts_simulations', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_data',
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('metric_value', sa.Float(precision=53), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'asset_id', 'source', 'metric_name')
    )
    op.create_index(op.f('ix_market_data_timestamp'), 'market_data', ['timestamp'], unique=False)
    op.create_table('unified_state_vectors',
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('state_vector', postgresql.ARRAY(sa.Float(precision=53)), nullable=False),
    sa.Column('vector_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'asset_id')
    )
    op.create_index(op.f('ix_unified_state_vectors_timestamp'), 'unified_state_vectors', ['timestamp'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_config_id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('trade_type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=28, scale=18), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=28, scale=18), nullable=False),
    sa.Column('fees', sa.NUMERIC(precision=28, scale=18), nullable=True),
    sa.Column('exchange', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['agent_config_id'], ['agent_configurations.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_index(op.f('ix_unified_state_vectors_timestamp'), table_name='unified_state_vectors')
    op.drop_table('unified_state_vectors')
    op.drop_index(op.f('ix_market_data_timestamp'), table_name='market_data')
    op.drop_table('market_data')
    op.drop_table('agent_configurations')
    op.drop_table('assets')
    # ### end Alembic commands ###
