name: Production Deployment

on:
  push:
    branches:
      - main
      - Testing-stabilization-and-launch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Deploy to Cloud Run and Firebase'
        run: |
          # Use secrets for the env file
          echo "${{ secrets.PROD_ENV_YAML }}" > env.production.yaml
          chmod +x deploy-production.sh
          ./deploy-production.sh
